In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_parquet("../data/processed/merged_dataset.parquet")

df.head()

,Season,Race,Track,Name,Length,Surface,Finish,Start,Car,Driver,...,Laps,Led,Status,Team,S1,S2,S3,Rating,Win,Series
0,1949,1,Charlotte Speedway,150 Miles at Charlotte Speedway,0.75,dirt,1.0,12.0,34,Jim Roper,...,197.0,47.0,running,R.B. McIntosh (Owner),NaN,NaN,NaN,NaN,1.0,Cup
1,1949,1,Charlotte Speedway,150 Miles at Charlotte Speedway,0.75,dirt,2.0,5.0,47,Fonty Flock,...,NaN,0.0,running,Grady Cole (Owner),NaN,NaN,NaN,NaN,0.0,Cup
2,1949,1,Charlotte Speedway,150 Miles at Charlotte Speedway,0.75,dirt,3.0,3.0,22,Red Byron,...,NaN,0.0,running,Raymond Parks (Owner),NaN,NaN,NaN,NaN,0.0,Cup
3,1949,1,Charlotte Speedway,150 Miles at Charlotte Speedway,0.75,dirt,4.0,14.0,2,Sam Rice,...,NaN,0.0,running,Rice Racing,NaN,NaN,NaN,NaN,0.0,Cup
4,1949,1,Charlotte Speedway,150 Miles at Charlotte Speedway,0.75,dirt,5.0,2.0,90,Tim Flock,...,NaN,0.0,running,Buddy Elliott (Owner),NaN,NaN,NaN,NaN,0.0,Cup

In [3]:
feature_df = df.copy()

In [4]:
print(feature_df.shape)

(181617, 22)

In [5]:
feature_df["Driver_Experience"] = (
    feature_df.groupby("Driver")["Driver"]
              .transform("count")
)

In [6]:
feature_df[["Driver", "Driver_Experience"]].head(10)

           Driver  Driver_Experience
0       Jim Roper                  2
1     Fonty Flock                153
2       Red Byron                 15
3        Sam Rice                  2
4       Tim Flock                187
5    Archie Smith                  2
6   Sterling Long                  3
7     Slick Smith                 49
8   Curtis Turner                184
9  Jimmy Thompson                 47

In [7]:
feature_df["Driver_Experience"].isnull().sum()

np.int64(0)

In [8]:
feature_df[["Driver", "Driver_Experience"]].head(10)

           Driver  Driver_Experience
0       Jim Roper                  2
1     Fonty Flock                153
2       Red Byron                 15
3        Sam Rice                  2
4       Tim Flock                187
5    Archie Smith                  2
6   Sterling Long                  3
7     Slick Smith                 49
8   Curtis Turner                184
9  Jimmy Thompson                 47

In [9]:
feature_df = feature_df.sort_values(
    by=["Season", "Race"]
).reset_index(drop=True)

In [10]:
feature_df[["Season", "Race", "Driver"]].head(20)

    Season  Race           Driver
0     1949     1        Jim Roper
1     1949     1      Fonty Flock
2     1949     1        Red Byron
3     1949     1         Sam Rice
4     1949     1        Tim Flock
5     1949     1     Archie Smith
6     1949     1    Sterling Long
7     1949     1      Slick Smith
8     1949     1    Curtis Turner
9     1949     1   Jimmy Thompson
10    1949     1       Buck Baker
11    1949     1       Bill Blair
12    1949     1       Jack Smith
13    1949     1   Sara Christian
14    1949     1      John Barker
15    1949     1  Jimmie Lewallen
16    1949     1        Lee Petty
17    1949     1     Skimp Hersey
18    1949     1        Bob Smith
19    1949     1      Otis Martin

In [11]:
feature_df["Driver_Avg_Finish"] = (
    feature_df.groupby("Driver")["Finish"]
    .transform(lambda x: x.shift().expanding().mean())
)

In [12]:
feature_df[
    ["Driver", "Season", "Race", "Finish", "Driver_Avg_Finish"]
].head(20)

             Driver  Season  Race  Finish  Driver_Avg_Finish
0         Jim Roper    1949     1     1.0                NaN
1       Fonty Flock    1949     1     2.0                NaN
2         Red Byron    1949     1     3.0                NaN
3          Sam Rice    1949     1     4.0                NaN
4         Tim Flock    1949     1     5.0                NaN
5      Archie Smith    1949     1     6.0                NaN
6     Sterling Long    1949     1     7.0                NaN
7       Slick Smith    1949     1     8.0                NaN
8     Curtis Turner    1949     1     9.0                NaN
9    Jimmy Thompson    1949     1    10.0                NaN
10       Buck Baker    1949     1    11.0                NaN
11       Bill Blair    1949     1    12.0                NaN
12       Jack Smith    1949     1    13.0                NaN
13   Sara Christian    1949     1    14.0                NaN
14      John Barker    1949     1    15.0                NaN
15  Jimmie Lewallen    1949     1    16.0                NaN
16        Lee Petty    1949     1    17.0                NaN
17     Skimp Hersey    1949     1    18.0                NaN
18        Bob Smith    1949     1    19.0                NaN
19      Otis Martin    1949     1    20.0                NaN

In [13]:
feature_df["Driver_Avg_Finish"].isnull().sum()

np.int64(4372)

In [14]:
feature_df["Driver_Avg_Rating"] = (
    feature_df.groupby("Driver")["Rating"]
              .transform(lambda x: x.shift().expanding().mean())
)

In [15]:
feature_df[
    ["Driver", "Rating", "Driver_Avg_Rating"]
].head(20)

             Driver  Rating  Driver_Avg_Rating
0         Jim Roper     NaN                NaN
1       Fonty Flock     NaN                NaN
2         Red Byron     NaN                NaN
3          Sam Rice     NaN                NaN
4         Tim Flock     NaN                NaN
5      Archie Smith     NaN                NaN
6     Sterling Long     NaN                NaN
7       Slick Smith     NaN                NaN
8     Curtis Turner     NaN                NaN
9    Jimmy Thompson     NaN                NaN
10       Buck Baker     NaN                NaN
11       Bill Blair     NaN                NaN
12       Jack Smith     NaN                NaN
13   Sara Christian     NaN                NaN
14      John Barker     NaN                NaN
15  Jimmie Lewallen     NaN                NaN
16        Lee Petty     NaN                NaN
17     Skimp Hersey     NaN                NaN
18        Bob Smith     NaN                NaN
19      Otis Martin     NaN                NaN

In [16]:
feature_df["Team_Avg_Rating"] = (
    feature_df.groupby("Team")["Rating"]
              .transform(lambda x: x.shift().expanding().mean())
)

In [17]:
feature_df[
    ["Team", "Rating", "Team_Avg_Rating"]
].head(20)

                       Team  Rating  Team_Avg_Rating
0     R.B. McIntosh (Owner)     NaN              NaN
1        Grady Cole (Owner)     NaN              NaN
2     Raymond Parks (Owner)     NaN              NaN
3               Rice Racing     NaN              NaN
4     Buddy Elliott (Owner)     NaN              NaN
5       Frank Smith (Owner)     NaN              NaN
6               Long Racing     NaN              NaN
7       Slick Smith (Owner)     NaN              NaN
8     Curtis Turner (Owner)     NaN              NaN
9    Bruce Thompson (Owner)     NaN              NaN
10     Penny Mullis (Owner)     NaN              NaN
11    R.B. McIntosh (Owner)     NaN              NaN
12                              NaN              NaN
13  Frank Christian (Owner)     NaN              NaN
14                              NaN              NaN
15  Jimmie Lewallen (Owner)     NaN              NaN
16        Petty Enterprises     NaN              NaN
17     Skimp Hersey (Owner)     NaN              NaN
18                              NaN              NaN
19                              NaN              NaN

In [18]:
feature_df["Make_Avg_Rating"] = (
    feature_df.groupby("Make")["Rating"]
              .transform(lambda x: x.shift().expanding().mean())
)

In [19]:
feature_df[
    ["Make", "Rating", "Make_Avg_Rating"]
].head(20)

          Make  Rating  Make_Avg_Rating
0      Lincoln     NaN              NaN
1       Hudson     NaN              NaN
2   Oldsmobile     NaN              NaN
3   Oldsmobile     NaN              NaN
4   Oldsmobile     NaN              NaN
5         Ford     NaN              NaN
6       Hudson     NaN              NaN
7   Oldsmobile     NaN              NaN
8        Buick     NaN              NaN
9     Chrysler     NaN              NaN
10      Kaiser     NaN              NaN
11     Lincoln     NaN              NaN
12        Ford     NaN              NaN
13        Ford     NaN              NaN
14      Kaiser     NaN              NaN
15        Ford     NaN              NaN
16       Buick     NaN              NaN
17        Ford     NaN              NaN
18  Oldsmobile     NaN              NaN
19        Ford     NaN              NaN

In [20]:
feature_df["Track_Avg_Rating"] = (
    feature_df.groupby("Track")["Rating"]
              .transform(lambda x: x.shift().expanding().mean())
)

In [21]:
feature_df[
    ["Track", "Rating", "Track_Avg_Rating"]
].head(20)

                 Track  Rating  Track_Avg_Rating
0   Charlotte Speedway     NaN               NaN
1   Charlotte Speedway     NaN               NaN
2   Charlotte Speedway     NaN               NaN
3   Charlotte Speedway     NaN               NaN
4   Charlotte Speedway     NaN               NaN
5   Charlotte Speedway     NaN               NaN
6   Charlotte Speedway     NaN               NaN
7   Charlotte Speedway     NaN               NaN
8   Charlotte Speedway     NaN               NaN
9   Charlotte Speedway     NaN               NaN
10  Charlotte Speedway     NaN               NaN
11  Charlotte Speedway     NaN               NaN
12  Charlotte Speedway     NaN               NaN
13  Charlotte Speedway     NaN               NaN
14  Charlotte Speedway     NaN               NaN
15  Charlotte Speedway     NaN               NaN
16  Charlotte Speedway     NaN               NaN
17  Charlotte Speedway     NaN               NaN
18  Charlotte Speedway     NaN               NaN
19  Charlotte Speedway     NaN               NaN

In [22]:
def classify_track(length):
    if length < 1:
        return "Short Track"
    elif length < 2:
        return "Intermediate"
    else:
        return "Superspeedway"

feature_df["Track_Type"] = feature_df["Length"].apply(classify_track)

In [23]:
feature_df[["Length", "Track_Type"]].head(20)

    Length   Track_Type
0     0.75  Short Track
1     0.75  Short Track
2     0.75  Short Track
3     0.75  Short Track
4     0.75  Short Track
5     0.75  Short Track
6     0.75  Short Track
7     0.75  Short Track
8     0.75  Short Track
9     0.75  Short Track
10    0.75  Short Track
11    0.75  Short Track
12    0.75  Short Track
13    0.75  Short Track
14    0.75  Short Track
15    0.75  Short Track
16    0.75  Short Track
17    0.75  Short Track
18    0.75  Short Track
19    0.75  Short Track

In [24]:
def classify_start(pos):
    if pos <= 5:
        return "Front"
    elif pos <= 15:
        return "Mid"
    else:
        return "Back"

feature_df["Start_Category"] = feature_df["Start"].apply(classify_start)

In [25]:
feature_df[["Start", "Start_Category"]].head(20)

    Start Start_Category
0    12.0            Mid
1     5.0          Front
2     3.0          Front
3    14.0            Mid
4     2.0          Front
5     NaN           Back
6     NaN           Back
7     NaN           Back
8     6.0            Mid
9     NaN           Back
10    NaN           Back
11    8.0            Mid
12    NaN           Back
13   13.0            Mid
14    NaN           Back
15    NaN           Back
16    9.0            Mid
17    NaN           Back
18    NaN           Back
19    4.0          Front

In [26]:
feature_df.columns

Index(['Season', 'Race', 'Track', 'Name', 'Length', 'Surface', 'Finish',
       'Start', 'Car', 'Driver', 'Make', 'Pts', 'Laps', 'Led', 'Status',
       'Team', 'S1', 'S2', 'S3', 'Rating', 'Win', 'Series',
       'Driver_Experience', 'Driver_Avg_Finish', 'Driver_Avg_Rating',
       'Team_Avg_Rating', 'Make_Avg_Rating', 'Track_Avg_Rating', 'Track_Type',
       'Start_Category'],
      dtype='str')

In [27]:
feature_df.to_parquet(
    "../data/processed/feature_engineered.parquet",
    index=False
)

print("✅ Feature engineered dataset saved successfully!")

✅ Feature engineered dataset saved successfully!